name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr
        
    - name: build for test
      run: g++ -DUNIT_TEST -Wall -Wextra -fprofile-arcs -ftest-coverage -o testchecker ./Sender/test-validation.cpp ./Sender/BSM_SignalProvider.c ./Sender/BSM_TestDoubles.c
         
    - name: sender test run
      run: ./testchecker

    - name: build receiver test
      run: g++ -Wall -Wextra -o Receiver_Test ./BMS_Reciever/test_Receiver.cpp ./BMS_Reciever/BMS_operation_manager.cpp ./BMS_Reciever/BMS_Receiver.cpp

    - name: receiver test run
      run: ./Receiver_Test

    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 1
     
    - name: Install boost
      run: sudo apt-get install libboost-thread-dev

    - name: build for production
      run: g++ -Wall -Wextra -o production ./Sender/main.c ./Sender/BSM_SignalProvider.c

    - name: build for Receiver
      run: g++ -Wall -Wextra -o Receiver ./BMS_Reciever/BMS_operation_manager.cpp ./BMS_Reciever/BMS_Receiver.cpp ./BMS_Reciever/BMS_Receiver_main.cpp
        
    - name: production code run
      run: ./production | ./Receiver
